name: terraform-apply

on:
  issue_comment:
    types: [created]

jobs:

  terraform-apply-dev:
    # Only run for comments starting with "terraform apply dev" in a pull request.
    if: >
      startsWith(github.event.comment.body, 'terraform apply dev')
      && startsWith(github.event.issue.pull_request.url, 'https://')
  
    name: terraform-apply-dev
    runs-on: ubuntu-latest

    env:
      WORKSPACE: 'dev'
      AWS_REGION: 'us-east-1'
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_K_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S_ID }}
      # CHECKOV_API_KEY: ${{ secrets.CHECKOV_API_KEY }}
    
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 'Load PR Details'
        id: load-pr
        run: |
          set -eu
          echo ${{ github.event.issue.pull_request.url }}
          echo ${{ secrets.CROSS_REPO_TOKEN }}
          resp=$(curl -sSf \
            --url ${{ github.event.issue.pull_request.url }} \
            --header 'Authorization: Bearer ${{ secrets.CROSS_REPO_TOKEN }}' \
            --header 'Accept: application/vnd.github+json')
          sha=$(jq -r '.head.sha' <<< "$resp")
          echo "head_sha=$sha" >> $GITHUB_OUTPUT
          comments_url=$(jq -r '.comments_url' <<< "$resp")
          echo "comments_url=$comments_url" >> $GITHUB_OUTPUT
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # By default (in a non-pull request build) you get HEAD of 'master'
          ref: ${{ steps.load-pr.outputs.head_sha }}
          submodules: 'true'
          token: ${{ secrets.GITHUB_TOKEN }} # Needed for private submodules
      
      - name: Build Workspace / Environment
        id: build-environment
        run: |
          cd environments/$WORKSPACE/.onekloud_init
          make
          ls -la ../
          cat ../terraform.tfvars

      - name: Setup AWSCli
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1.0.6
        with:
          version: 2     # default
          verbose: false # default
          arch: amd64    # allowed values: amd64, arm64
      
      - name: Setup Terraform
        id: terraform-setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1
          terraform_wrapper: false
      
      - name: terraform init
        id: terraform-init
        run: terraform -chdir=environments/$WORKSPACE init
      
      - name: terraform format
        id: terraform-format
        run: terraform -chdir=environments/$WORKSPACE fmt -check -diff
      
      - name: terraform validate
        id: terraform-validate
        run: terraform -chdir=environments/$WORKSPACE validate
      
      - name: terraform plan
        id: terraform-plan
        run: |
          set -eu
          terraform -chdir=environments/$WORKSPACE plan
          terraform_plan_out=$(terraform -chdir=environments/$WORKSPACE plan -no-color -out tfplan.binary)
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "tf_plan_out<<$EOF" >> $GITHUB_OUTPUT
          echo "$terraform_plan_out" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
      
      - name: Convert Terraform Plan To JSON
        id: terraform-json
        run: terraform -chdir=environments/$WORKSPACE show -json tfplan.binary | jq -r '.' > tfplan.json
      
      - name: Setup OPA
        id: setup-opa
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest
      
      - name: Validate Terraform Plan Against OPA GENERAL [ WARN ] rules
        id: validate-opa-warn
        run: opa exec --bundle environments/$WORKSPACE/opa-policies --decision general/warn tfplan.json | jq -r '.result[0].result'
      
      - name: Validate Terraform Plan Against OPA GENERAL [ DENY ] rules
        id: validate-opa-deny
        run: |
          opa exec --bundle environments/$WORKSPACE/opa-policies --decision general/deny tfplan.json | jq -r '.result[0].result'
          has_failures=$(opa exec --bundle environments/$WORKSPACE/opa-policies --decision general/deny tfplan.json | jq -r '.result[0].result[0]')
          if [[ $has_failures == *"GENERAL"* ]]
          then
             exit 1
          fi
      
      - name: Install PIP3
        id: install-pip3
        run: |
          sudo apt-get -y install python3-pip
      
      - name: Install Checkov
        id: install-checkov
        run: pip3 install checkov
      
      - name: Static Code Security Analysis
        id: run-checkov
        run: checkov -f tfplan.json -s --quiet # --bc-api-key $CHECKOV_API_KEY
      
      - name: terraform apply
        id: terraform-apply
        run: |
          set -eu
          terraform_apply_out=$(terraform -chdir=environments/$WORKSPACE apply tfplan.binary)
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "tf_apply_out<<$EOF" >> $GITHUB_OUTPUT
          echo "$terraform_apply_out" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
